# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

""" 主窗口布局代码v1版本 """
class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(923, 794)
        mainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 730, 891, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.image_show_label = QtWidgets.QGroupBox(self.centralwidget)
        self.image_show_label.setGeometry(QtCore.QRect(580, 390, 321, 331))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.image_show_label.setFont(font)
        self.image_show_label.setObjectName("image_show_label")
        self.image_show = QtWidgets.QLabel(self.image_show_label)
        self.image_show.setGeometry(QtCore.QRect(30, 40, 261, 261))
        self.image_show.setText("")
        self.image_show.setPixmap(QtGui.QPixmap("E:/vscode_work/py_spider/images/动画榜.png"))
        self.image_show.setScaledContents(True)
        self.image_show.setWordWrap(False)
        self.image_show.setObjectName("image_show")
        self.console_label_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.console_label_2.setGeometry(QtCore.QRect(20, 10, 881, 371))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.console_label_2.setFont(font)
        self.console_label_2.setFlat(False)
        self.console_label_2.setCheckable(False)
        self.console_label_2.setObjectName("console_label_2")
        self.console_show = QtWidgets.QTextEdit(self.console_label_2)
        self.console_show.setGeometry(QtCore.QRect(20, 30, 841, 291))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.console_show.setFont(font)
        self.console_show.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.console_show.setLineWidth(0)
        self.console_show.setMidLineWidth(0)
        self.console_show.setCursorWidth(1)
        self.console_show.setObjectName("console_show")
        self.export_btn = QtWidgets.QPushButton(self.console_label_2)
        self.export_btn.setGeometry(QtCore.QRect(450, 330, 93, 28))
        self.export_btn.setObjectName("export_btn")
        self.reset_show = QtWidgets.QPushButton(self.console_label_2)
        self.reset_show.setGeometry(QtCore.QRect(340, 330, 93, 28))
        self.reset_show.setObjectName("reset_show")
        self.input_label = QtWidgets.QGroupBox(self.centralwidget)
        self.input_label.setGeometry(QtCore.QRect(20, 390, 541, 191))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.input_label.setFont(font)
        self.input_label.setObjectName("input_label")
        self.url_label = QtWidgets.QLabel(self.input_label)
        self.url_label.setGeometry(QtCore.QRect(20, 60, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.url_label.setFont(font)
        self.url_label.setObjectName("url_label")
        self.xpath_label = QtWidgets.QLabel(self.input_label)
        self.xpath_label.setGeometry(QtCore.QRect(10, 110, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.xpath_label.setFont(font)
        self.xpath_label.setObjectName("xpath_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.input_label)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 40, 441, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.url_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.url_input.setFont(font)
        self.url_input.setAcceptDrops(True)
        self.url_input.setToolTip("")
        self.url_input.setAutoFillBackground(False)
        self.url_input.setText("")
        self.url_input.setCursorPosition(0)
        self.url_input.setObjectName("url_input")
        self.verticalLayout.addWidget(self.url_input)
        self.xpath_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setKerning(True)
        self.xpath_input.setFont(font)
        self.xpath_input.setMouseTracking(True)
        self.xpath_input.setCursorPosition(0)
        self.xpath_input.setClearButtonEnabled(False)
        self.xpath_input.setObjectName("xpath_input")
        self.verticalLayout.addWidget(self.xpath_input)
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(350, 600, 93, 28))
        self.start_btn.setObjectName("start_btn")
        self.exit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.exit_btn.setGeometry(QtCore.QRect(460, 600, 93, 28))
        self.exit_btn.setObjectName("exit_btn")
        self.wc_sel = QtWidgets.QCheckBox(self.centralwidget)
        self.wc_sel.setGeometry(QtCore.QRect(220, 600, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.wc_sel.setFont(font)
        self.wc_sel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.wc_sel.setObjectName("wc_sel")
        self.list_choose = QtWidgets.QComboBox(self.centralwidget)
        self.list_choose.setGeometry(QtCore.QRect(110, 600, 87, 22))
        self.list_choose.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.list_choose.setEditable(False)
        self.list_choose.setObjectName("list_choose")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.image_show_label.setTitle(_translate("mainWindow", "生成的词云"))
        self.console_label_2.setTitle(_translate("mainWindow", "抓取数据显示"))
        self.console_show.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.console_show.setPlaceholderText(_translate("mainWindow", "这里将显示爬取内容~"))
        self.export_btn.setText(_translate("mainWindow", "导出"))
        self.reset_show.setText(_translate("mainWindow", "重置"))
        self.input_label.setTitle(_translate("mainWindow", "输入"))
        self.url_label.setText(_translate("mainWindow", "网址:"))
        self.xpath_label.setText(_translate("mainWindow", "xpath:"))
        self.url_input.setPlaceholderText(_translate("mainWindow", "请输入网址"))
        self.xpath_input.setPlaceholderText(_translate("mainWindow", "请输入xpath路径"))
        self.start_btn.setText(_translate("mainWindow", "爬取"))
        self.exit_btn.setText(_translate("mainWindow", "退出程序"))
        self.wc_sel.setText(_translate("mainWindow", "制作词云"))
